server:
  servlet:
    context-path: /
  port: 8080
spring:
  application:
    name: SmartConstruction
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/smartuser?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-auto-commit: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录s
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
devtools:
  remote:
    restart:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:com/hunau/*Mapper.xml
  type-aliases-package: com.hunau.bean
http:
  max-total: 300
  default-max-per-route: 50
  connect-timeout: 1000
  connection-request-timeout: 500
  socket-timeout: 5000


